### ISSUE TITLE
CCA-Portable-3.1.4 Pin to Taskbar Fails

### ISSUE THREAD

**Issue by 1John419** [ThePacielloGroup/CCAe#231]
OS: Windows 10 Pro 64 bit
Version 21H1 (OS Build 19043.1348)

1. Double click CCA-Portable-3.1.4.exe
2. Right click CCA icon in taskbar
3. Click Pin to taskbar
4. Close CCA
5. Click pinned CCA icon in taskbar

Expected behavior:
CCA opens.

Instead the following error occurs:

![Screenshot 2021-12-04 152554](https://user-images.githubusercontent.com/46386951/144726547-bbabd34e-c4dc-4441-a396-1be43127e902.png)

This issue does NOT occur with the MSI installed version; only the Portable version.

**Comment by ferllings** [comment]
The problem is related to how the portable app is working:
When you run the portable binary, it "unzip" the all content into a AppData/Temp folder.
When you pin CCA, it will reference the .exe inside this Temp folder, which is removed when closed.

The solution is to edit the pin yourself, and target the original portable .exe
<img width="540" alt="Screenshot 2023-10-06 at 13 31 58" src="https://github.com/ThePacielloGroup/CCAe/assets/2118130/d2f2705a-8a47-44a4-ae0f-810ebd7d84f4">

**Comment by 1John419** [comment]
Thank you for the insight. The method described does indeed work. However, I found a better solution was to copy and rename the temporary CCA folder to permanent location, execute CCA, and pin from there. App launches much faster. Many portable apps simply zip the program directory. That might be a better approach for CCA...
