### ISSUE TITLE
Could calculated ratio show 2 digits (rather than 1) after the decimal point?

### ISSUE THREAD

**Issue by RussellJQA** [ThePacielloGroup/CCAe#78]
Could the calculated ratio show 2 digits (rather than 1) after the decimal point?

Thanks.

**Comment by robsonsobral** [comment]
It's easier to know how much to push/pull the slider if we know how far we are from the desired value.

**Comment by RussellJQA** [comment]
I think @robsonsobral has a good point. When dragging the Red/Blue/Green/Alpha sliders, it can be helpful to know how far one is from the target value.

And 2 decimal places is in accord with what other tools display. For example, aXe, WAVE, WebAIM, and Tanaguru all report 2+ decimal places. Clients used to seeing 2 decimal places reported may wonder why we only report 1.

**Comment by sasgrw** [comment]
Is the 2nd decimal point truncated?  Is a value of 4.49 reported as 4.4?  I'm guessing so because rounding it up to 4.5, while mathematically correct, would mean the ratio passes when it shouldn't.  Even worst if 4.46 were rounded up to 4.5.  Having two decimals is very handy.  You can always make it an option if you think some people want it simple.

**Comment by patrickhlauke** [comment]
from the referenced discussion in https://github.com/w3c/wcag/issues/200, the second decimal point is not significant/certain enough. indeed, any difference in contrast that is only down to something below 0.1 is practically imperceptible. for this reason, we decided to only stick to 1 significant decimal point.

as for rounding, CCA does indeed round things up/down. however, to determine pass/fail, it looks at the non-rounded value - which is why #777 on #FFF for instance is reported as:

Foreground: #777777
Background: #FFFFFF
The contrast ratio is: just below 4.5:1 (4.478:1)
1.4.3 Contrast (Minimum) (AA)
    Pass for large text only. Fail for regular text
1.4.6 Contrast (Enhanced) (AAA)
    Fail for large and regular text
1.4.11 Non-text Contrast (AA)
    Pass for UI components and graphical objects

On a more general note, I'd recommend not getting too hung up on the pseudo-scientific accuracy of running the contrast calculation with more than a single decimal. if you're worried that a particular color combination may pass or fail depending on the rounding, that's more an indication that your color combination really is on the cusp of the bare minimum...

**Comment by RussellJQA** [comment]
I think some customers (those whose Websites are being tested) prefer 2, probably because that's what they'd seen reported elsewhere.
